[package]
name = "xandikos"
version = "0.2.8"
authors = [ "Jelmer Vernooij <jelmer@jelmer.uk>"]
edition = "2021"
license = "GPL-3.0+"
description = "Lightweight CalDAV/CardDAV server"
repository = "https://github.com/jelmer/xandikos.git"
homepage = "https://github.com/jelmer/xandikos"

[dependencies]
pyo3 = { version = "0.18", features=["auto-initialize"]}
clap = "4"
tokio = { version = "1", features = ["full"] }
